CREATE TABLE `db_turma_202400207`.`tbl_alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `sobrenome` VARCHAR(255) NULL,
  `nacionalidade` VARCHAR(255) NULL,
  `profissao` VARCHAR(255) NULL,
  `estado_civil` VARCHAR(255) NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(255) NULL,
  `endereco` VARCHAR(255) NULL,
  `numero_endereco` VARCHAR(255) NULL,
  `bairro` VARCHAR(255) NULL,
  `cidade` VARCHAR(255) NULL,
  `estado` VARCHAR(255) NULL,
  `cep` VARCHAR(255) NULL,
  `altura` VARCHAR(255) NULL,
  `peso` VARCHAR(255) NULL,
  `apelido` VARCHAR(255) NULL,
  `cor_da_pele` VARCHAR(255) NULL,
  `genero` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));
